AWSTemplateFormatVersion: 2010-09-09

Description: Template de criação de uma instancia EC2 com liberação do SSH

Parameters: 
  KeyName: 
    Description: KeyPairCloudFormation.pem
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: KeyPairCloudFormation.pem

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0be2609ba883822ec
      KeyName: !Ref KeyName
      SecurityGroups:
       - Ref: InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: My CF Instance
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
